# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      ghmariadb:
        image: mariadb:10.9.2-jammy
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: 'lars'
          MYSQL_USER: 'infoBuser'
          MYSQL_PASSWORD: 'giich2Xu'
          MYSQL_DATABASE: 'infoBlatt'
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: >
        ./mvnw 
        -B
        -Dspring.datasource.url="jdbc:mariadb://localhost:3306/infoBlatt"
        dependency:go-offline
        clean verify
